x: 'geno1'
y: 'intermediate1'
geno1:
  prepare_XT:
    geno-mean:
      name-format: '../../data/fake_data/genotype/genotest1.genotype-mean.{chr}.txt.gz'
    snp-list:
      name-format: '../../data/fake_data/genotype/genotest1.snp-list.{chr}.gz'
    chr-list: 'chr,1:22'
intermediate1:
  prepare_betaI:
    beta-ss: '../../data/fake_data/beta/betatest1-genotest1.summary-statistic.txt.gz'
    header: 0  # no header = 0, with header = 1
    chr-pos-ref-alt-reffrq-info-rs-pval-effalt: '1,2,3,4,5,6,7,8,9'
  nsamples: 20000
ldpred-dir: '../../../ldpred/ldpred'
ldpred:
  num-SNPs-per-xMb: 1
  causal-fraction: '1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001'
