import argparse
parser = argparse.ArgumentParser(prog='ldpred_wrapper.py', description='''
    This script is a wrapper of ldpred/LDpred.py. Besides the input of LDpred.py,
    it also takes ld-radius in YAML format
''')
parser.add_argument('--coord', help = 'HDF5 file generated by ldpred/coord_genotypes.py')
parser.add_argument('--causal_fraction', help = 'a list of causal fraction (hyperparameters) used by ldpred/LDpred.py')
parser.add_argument('--out', help = 'output prefix')
parser.add_argument('--nsamples', help = 'sample size of GWAS summary statistics')
parser.add_argument('--ld_radius', help = 'ld-radius in YAML format')
parser.add_argument('--ldpred_dir', help = 'directory of Ldpred.py')
parser.add_argument('--prefix_of_pickle', help = 'prefix of generated pickle file')
args = parser.parse_args()

import yaml, os

f = open(args.ld_radius, 'r')
radius = yaml.load(f)
radius = radius['ld-radius']
f.close()

cmd = 'python {dir}/LDpred.py \
        --coord {coord} \
        --ld_radius {radius} \
        --PS {fraction} \
        --N {n} \
        --local_ld_file_prefix {prefix} \
        --out {out}'.format(dir = args.ldpred_dir,
                            coord = args.coord,
                            radius = int(radius),
                            fraction = args.causal_fraction,
                            n = args.nsamples,
                            prefix = args.prefix_of_pickle,
                            out = args.out)
print('=============== LDpred wrapper START ================')
print('Do:')
print(cmd)
os.system(cmd)
print('=============== LDpred wrapper FINISH ===============')
