x1: 'wtccc_t2d'
x2: 'wtccc_ctrl'
y: 'fastGlu'

wtccc_t2d__wtccc_ctrl:
  name-format: '../step1/output-combine_XT_YT/{replace}/merge_QC'
fastGlu__wtccc_t2d__wtccc_ctrl:
  name-format: '../step1/output-run_step1/{replace}/ldpred_LDpred_p'

## other parameters
ldpred-dir: '../../../ldpred/ldpred'
ldpred:
  causal-fraction: '1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001'
yi-pattern: 'covar_LDpred_:.txt'
functional-subsetting:
  pval-theshold: 0.01
sigificance-subsetting:
  pval-theshold: 5e-5
