x1: 'geno1_case'
x2: 'geno2_ctrl'
y: 'intermediate1'

chr-list: 'chr,1:3'

geno1_case__geno2_ctrl:
  name-format: '../step1/output-combine_XT_YT/{replace}/merge_QC'
intermediate1__geno1_case__geno2_ctrl:
  name-format: '../step1/output-run_step1/{replace}/ldpred.{chr}_LDpred_p'

## other parameters
ldpred-dir: '../../../ldpred/ldpred'
ldpred:
  causal-fraction: '1,0.3,0.1,0.03,0.01,0.003,0.001,0.0003,0.0001'
chr-list: 'chr,1:3'
yi-pattern: 'covar_LDpred_:.txt'
functional-subsetting:
  pval-theshold: 1
