x1: 'wtccc_cad'
x2: 'wtccc_ctrl'
y: 'fastGlu'
tissue-type: 'Artery_Coronary,DGN-HapMap-2015,Whole_Blood,Cells_EBV-transformed_lymphocytes,Thyroid,Stomach,Small_Intestine_Terminal_Ileum,Esophagus_Muscularis,Spleen,Pancreas,Esophagus_Gastroesophageal_Junction,Adrenal_Gland,Adipose_Visceral_Omentum,Adipose_Subcutaneous,Pituitary,Colon_Transverse,Esophagus_Mucosa,Liver,Lung,Muscle_Skeletal,Cells_Transformed_fibroblasts'  # can take multiple tissues (separate them by ',')

## data parameters
wtccc_cad__wtccc_ctrl:
  name-format: '../step1/output-combine_XT_YT/{replace}/merge_QC'
fastGlu__wtccc_t2d__wtccc_ctrl:
  name-format: '../step1/output-run_step1/{replace}/ldpred_LDpred_p'
  gene-set: 'IDE,HHEX,TTLL5,CCDC33'

## other parameters
gencode_annotation: '/mnt/gluster/home/yanyul/data/gencode/gencode.v19.chr_patch_hapl_scaff.annotation.gtf.gz'
chr-list: 'chr,1:22'
predixcan-dir: '/mnt/gluster/home/yanyul/repo/PrediXcan/Software/'
python2.7-dir: '/opt/anaconda/anaconda2/bin/'
ldpred:
  causal-fraction: '1,0.3,0.1'


## tissues
Artery_Coronary:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Artery_Coronary/gtex_v7_Artery_Coronary_imputed_europeans_tw_0.5_signif.db'
DGN-HapMap-2015:
  db: '/mnt/gluster/home/yanyul/data/predixcan/DGN-HapMap-2015/DGN-WB_0.5.db'
Whole_Blood:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Whole_Blood/gtex_v7_Whole_Blood_imputed_europeans_tw_0.5_signif.db'
Cells_EBV-transformed_lymphocytes:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Cells_EBV-transformed_lymphocytes/gtex_v7_Cells_EBV-transformed_lymphocytes_imputed_europeans_tw_0.5_signif.db'
Thyroid:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Thyroid/gtex_v7_Thyroid_imputed_europeans_tw_0.5_signif.db'
Stomach:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Stomach/gtex_v7_Stomach_imputed_europeans_tw_0.5_signif.db'
Small_Intestine_Terminal_Ileum:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Small_Intestine_Terminal_Ileum/gtex_v7_Small_Intestine_Terminal_Ileum_imputed_europeans_tw_0.5_signif.db'
Esophagus_Muscularis:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Esophagus_Muscularis/gtex_v7_Esophagus_Muscularis_imputed_europeans_tw_0.5_signif.db'
Spleen:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Spleen/gtex_v7_Spleen_imputed_europeans_tw_0.5_signif.db'
Pancreas:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Pancreas/gtex_v7_Pancreas_imputed_europeans_tw_0.5_signif.db'
Esophagus_Gastroesophageal_Junction:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Esophagus_Gastroesophageal_Junction/gtex_v7_Esophagus_Gastroesophageal_Junction_imputed_europeans_tw_0.5_signif.db'
Adrenal_Gland:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Adrenal_Gland/gtex_v7_Adrenal_Gland_imputed_europeans_tw_0.5_signif.db'
Adipose_Visceral_Omentum:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Adipose_Visceral_Omentum/gtex_v7_Adipose_Visceral_Omentum_imputed_europeans_tw_0.5_signif.db'
Adipose_Subcutaneous:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Adipose_Subcutaneous/gtex_v7_Adipose_Subcutaneous_imputed_europeans_tw_0.5_signif.db'
Pituitary:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Pituitary/gtex_v7_Pituitary_imputed_europeans_tw_0.5_signif.db'
Colon_Transverse:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Colon_Transverse/gtex_v7_Colon_Transverse_imputed_europeans_tw_0.5_signif.db'
Esophagus_Mucosa:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Esophagus_Mucosa/gtex_v7_Esophagus_Mucosa_imputed_europeans_tw_0.5_signif.db'
Liver:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Liver/gtex_v7_Liver_imputed_europeans_tw_0.5_signif.db'
Lung:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Lung/gtex_v7_Lung_imputed_europeans_tw_0.5_signif.db'
Muscle_Skeletal:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Muscle_Skeletal/gtex_v7_Muscle_Skeletal_imputed_europeans_tw_0.5_signif.db'
Cells_Transformed_fibroblasts:
  db: '/mnt/gluster/home/yanyul/data/predixcan/Cells_Transformed_fibroblasts/gtex_v7_Cells_Transformed_fibroblasts_imputed_europeans_tw_0.5_signif.db'
